### ISSUE TITLE
תרגיל מספר 3

### ISSUE THREAD

**Issue by ofekam** [tocodeil/react-course-examples#14]
האם צריך לתפוס כל לחיצה כולל לחיצות על מקשים כמו INSERT,HOME,SHIFT וכו?

**Comment by vnovick** [comment]
If you refer to the following: [exercise](https://github.com/tocodeil/react-course-examples/blob/master/17-lifecycle-lab/src/03-custominput.jsx), then capture only characters or symbols pressed. You can see a demo here: https://www.tocode.co.il/bundles/react/lessons/lifecycle-lab. 
No need to implement keypresses for Insert, home or shift.
