### ISSUE TITLE
unable to load jQuery/plugin

### ISSUE THREAD

**Issue by tomerz012** [tocodeil/react-course-examples#23]
here is what i tried so far...let me know what am i doing wrong :)
1. webpack added line, caused me to define the import in react with jQuery and not jquery - otherwise i would get :
Module not found: Error: Cannot resolve module 'expose' 

2. after fixing it, i got inside the zoomove, jQuery not defined, tried to change it in their code to window.jQuery but then it failed inside...
3. tried to remove it from webpack, and add it myself as you did in the classroom example....didn't work for me...still getting jQuery not defined

**Comment by vnovick** [comment]
Can you please post the code of what you've tried to do?

**Comment by tomerz012** [comment]
[tmp.txt](https://github.com/tocodeil/react-course-examples/files/673174/tmp.txt)

**Comment by ynonp** [comment]
1. I think jquery js should be in lowercase so try to use this for import:
```
import jQuery from 'jquery';
```

2. You may need to add the expose module with:

```
npm install --save expose-loader
```

**Comment by tomerz012** [comment]
now I'm getting:
ncaught ReferenceError: jquery is not defined
    at Object.<anonymous> (zoomove.min.js:9)
    at __webpack_require__ (bootstrap 922892a…:19)
    at Object.<anonymous> (02-zoomove.jsx:12)

tried to add it to the window in main.jsx as well...didn't work out.

**Comment by vnovick** [comment]
Have you added the loader in the following way?

```
module: {
  loaders: [
    { test: require.resolve("jquery"), loader: "expose-loader?$!expose-loader?jQuery" },
  ]
}
```

**Comment by tomerz012** [comment]
ynon suggested:
 { test: require.resolve("jquery"), loader: "expose?$!expose?jQuery" }

you're suggesting:
{ test: require.resolve("jquery"), loader: "expose-loader?$!expose-loader?jQuery" },

not sure what's the diff....anyhow, both does not work.

**Comment by ynonp-test** [comment]
The following files work for me:

// main.jsx

```
import React from 'react';
import ReactDOM from 'react-dom';
import $ from 'jquery';
import {} from 'zoomove/dist/zoomove.min';

const App = function(props) {
  return <p>Hello World</p>;
}

window.$ = $;

ReactDOM.render(<App />, document.querySelector('main'));
```

// webpack.config.js

```
// webpack.config.js
module.exports = {
  entry: 'main.jsx',
  output: {
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel', // 'babel-loader' is also a legal name to reference
        query: {
          presets: ['react', 'es2015'],
          plugins: ["transform-class-properties"]
        }
      },
      { test: require.resolve("jquery"), loader: "expose-loader?jQuery" }
    ]
  },
  resolve: {
    modulesDirectories: ['node_modules', 'src'],
    extensions: ['', '.js', '.jsx']
  },
};
```

// package.json
```
{
  "name": "react-demo-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.13.2",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-class-properties": "^6.11.5",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-react": "^6.11.1",
    "webpack": "^1.13.1"
  },
  "dependencies": {
    "expose-loader": "^0.7.1",
    "jquery": "^3.1.1",
    "react": "^15.3.0",
    "react-dom": "^15.3.0",
    "zoomove": "^1.2.1"
  }
}
```

**Comment by tomerz012** [comment]
:) didn't work for me...getting the same error....our package json and webpack config were exactly the same...i thought it might be something i did...so i copied your main.jsx, but i am getting the same error
does the jsx file should still be under src folder?

**Comment by ynonp** [comment]
This is my entire project folder. You can even run it by typing in the terminal: `webpack-dev-server --host 0.0.0.0` and click on the little "Play" button to see the hello world message

https://codepicnic.com/consoles/jquery-zoomov

If it still don't work we'll look at it together when we meet next

**Comment by tomerz012** [comment]
Hooray....managed to fix it....used something else....
here is how my webpack.config.js looks like now:

// webpack.config.js
var webpack = require("webpack");

module.exports = {
    entry: 'main.jsx',
    output: {
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel', // 'babel-loader' is also a legal name to reference
                query: {
                    presets: ['react', 'es2015'],
                    plugins: ["transform-class-properties"]
                }
            },
        ]
    },
    resolve: {
        modulesDirectories: ['node_modules', 'src'],
        extensions: ['', '.js', '.jsx']
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            jquery: "jquery"
        })
    ]

};
